user atom;
worker_processes 1;

error_log /var/log/nginx/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    log_format main '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
    sendfile on;
    keepalive_timeout 65;
    gzip on;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    upstream atom {
        server unix:/run/php-fpm/atom.sock;
    }

    server {

        listen 80;
        root /atom/src;

        # http://wiki.nginx.org/HttpCoreModule#server_name
        # _ means catch any, but it's better if you replace this with your server
        # name, e.g. archives.foobar.com
        server_name _;

        # Hide nginx version
        server_tokens off;

        client_max_body_size 72M;

        # Enable gzip compression for specific file types
        gzip on;
        gzip_comp_level 6;
        gzip_http_version 1.0;
        gzip_proxied any;
        gzip_disable "msie6";
        gzip_types text/css text/x-component application/x-javascript application/javascript text/javascript text/x-js text/richtext image/svg+xml text/plain text/xsd text/xsl text/xml image/bmp application/java application/msword application/vnd.ms-fontobject application/x-msdownload image/x-icon image/webp application/json application/vnd.ms-access application/vnd.ms-project application/x-font-otf application/vnd.ms-opentype application/vnd.oasis.opendocument.database application/vnd.oasis.opendocument.chart application/vnd.oasis.opendocument.formula application/vnd.oasis.opendocument.graphics application/vnd.oasis.opendocument.spreadsheet application/vnd.oasis.opendocument.text audio/ogg application/pdf application/vnd.ms-powerpoint application/x-shockwave-flash image/tiff application/x-font-ttf audio/wav application/vnd.ms-write application/font-woff application/font-woff2 application/vnd.ms-excel;

        # For image proxy
        resolver 1.1.1.1;

        # Serve static files directly, and route all other requests to index.php
        location / {
            try_files $uri /index.php$is_args$args;
        }

        # Block all web requests to hidden directories
        location ~ /\. {
            deny all;
            return 404;
        }
        # Block access to sensitive file types
        location ~* (\.yml|\.ini|\.tmpl)$ {
            deny all;
            return 404;
        }
        # Block access to PHP files in uploads and files directories
        location ~* /(?:uploads|files)/.*\.php$ {
            deny all;
            return 404;
        }
        # Block access to configuration files in uploads/r/*/conf/
        location ~* /uploads/r/(.*)/conf/ {
        }
        # Proxy requests to /uploads/r/* to an S3 bucket
        location ~* ^/uploads/r/(.*)$ {
            proxy_set_header Host archive-static.delos.space;
            proxy_pass $scheme://archive-static.delos.space/r/$1;
        }
        # Block access to the /private directory and serve files from /atom/src instead
        location ~ ^/private/(.*)$ {
            internal;
            alias /atom/src/$1;
        }
        # Serve PHP files for /index.php and /qubit_dev.php, but deny access to all other PHP files
        location ~ ^/(index|qubit_dev)\.php(/|$) {
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            fastcgi_pass atom;
        }
        # Deny access to all other PHP files
        location ~* \.php$ {
            deny all;
            return 404;
        }

    }

}
